src/components/Testimonial/Testimonial.js, src/components/Testimonial/testimonial.css, src/components/Testimonial/testimonial_data.js
I wrapped the entire rendering component in a **flex box div**. Changed the order of elements!
Tested on Firefox(61.0) and works fine!
=> tried fixing testimonials responsiveness

package-lock.json, package.json, src/App.js, src/components/Navigation/Navigation.js, src/index.js
added react router to implement login in navbar
=> react router in navbar

src/App.js, src/components/Login/login.css, src/components/SignUp/Signup.css, src/components/SignUp/Signup.js
The sign up page for the user with responsiveness
[Screenshot](https://screenshots.firefox.com/tw6HR4SmV5nf8nyy/localhost)
-  [x] My code follows the code style of this project.
=> sign up component added

.gitignore, package-lock.json, src/components/CardLayout/CardLayout.js, src/components/CardLayout/Components/Card.js, src/components/CardLayout/card_component.css, src/components/Contributors/Contributors.js, src/components/Contributors/contributor_component.css, src/components/Partners/Partners.js, src/components/Partners/partners.css, src/components/Testimonial/Testimonial.js, src/components/Testimonial/testimonial.css
Resolved the Testimonial and Card image problem for mobile view and
provided padding on sides for the same. Need to make changes (align in center for mobile view) for
contributor list and Supporters&Partners.
=> Made some of desired changes for the issue #19

.travis.yml
Fixes #36 
Included nodejs version to make the build pass
=> Fixed Travis CI  build

.flowconfig, package-lock.json, package.json
Integrated flow to the codebase
Fixes #28
=> added flow for typechecking

package.json, sw-precache-config.js
Added Service worker for the react application
Fixes #25
=> added service workers

package-lock.json, package.json, src/ignitus-Testimonial/Components/Testimonial.js, src/ignitus-Testimonial/Containers/TestimonialContainer.js, src/ignitus-Testimonial/selectors.js, src/ignitus-Testimonial/selectors.test.js
Added reselect to the project. Also refactored `ignitus-Testimonials` to utilize the new selector for selecting Testimonial data.
This sets the project up to begin to make use of memoized, composable selector functions to easily manage selecting specific entires from Redux state. 
Issue #22 
Created a selectors.test.js file to test that the selectors correctly pass data as expected. Also ran the app via `npm run build` and `npm run start` to verify testimonial data was still being mapped over.
=> Add reselect - #22

src/ignitus-Footer/Components/Footer.js, src/ignitus-Partners/Components/Partners.js
* Added URL's for partners and about us links
* Replace anchor tags with link and HashLink to avoid page refresh
* Modified links to homepage with leading slash
Fix links to proper URL's and replaced anchor tags with Link and HashLink in footer 
* Added URL's for partners and about us links
* Replace anchor tags with link and HashLink to avoid page refresh
* Modified links to homepage with leading slash
https://github.com/Ignitus/Ignitus-Client-Side-Development/issues/50
Checked the links from homepage and about us page.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
=> Added proper URL's for Footer

src/ignitus-Login/Components/login.js, src/ignitus-Login/Styles/style.css, src/ignitus-SignUp/Components/Signup.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Signup.js
#66
Change UI for Login/Signup for student and professor logins
make the forms look consistent
added some styling classes
Consider having reusable components
=> Change UI for Login/Signup forms

src/ignitus-About/Components/About.js, src/ignitus-Contributors/Components/Contributors.js, src/ignitus-Footer/Components/Footer.js, src/ignitus-GetStarted/Components/GetStarted.js, src/ignitus-Introduction/Components/Introduction.js, src/ignitus-Login/Components/login.js, src/ignitus-Navigation/Components/Navigation.js, src/ignitus-Partners/Components/Partners.js, src/ignitus-StudentSignUp/Components/Signup.js, src/ignitus-Testimonial/Components/Testimonial.js, src/ignitus-WhatWeDo/Components/Card.js, src/ignitus-WhatWeDo/Components/CardLayout.js, src/ignitus-WhatWeDo/Styles/style.css
I went through each of the components and converted those that had no need to extend React.Component to stateless functional components and did this across the board to maintain consistency. I also improved some of the image sizes by adding an object-fit property and adjusting the height and width accordingly. 
The component transformations were merely for consistency sake and writing cleaner code. Much of the changes I created could be considered "icing" or merely eslint pleasers, but i'd imagine they would be tedious tasks that you guys would likely rather not have done yourselves. 
Each page seems to be functioning the exact same. I personally didn't change any of the functionality or logic of any component, so there were no specific tests implemented. 
-*[√] Small nit-picky changes to …
=> Transformed RCC to RFC and improved image size/quality

src/ignitus-Testimonial/Components/Testimonial.js
- Refactored `goToPrevSlide` and `goToNextSlide` in `Testimonial.js` component to use functional `setState` as well as using the correct prop for `testimonialData`
- removed a console log from a lifecycle method within `Testimonial.js`
- fixed a simple linting issue regarding the placement of `componentDidUpdate` by moving it after `componentDidMount`
- This fixes an issue where clicking on the carousel navigation buttons would result in an error
- testing was only done through running the app and using the related feature
- n/a
=> Bugfix: `goToPrevSlide` and `goToNextSlide` methods in Testimonial.js component

src/helpers/validate.js, src/ignitus-StudentLogin/Components/Login.js
I added a validation class in the helper folder
I turned the Login class to a stateful component
I added validation   
To make validation to login form
=> Login form validation

src/ignitus-GetStarted/Components/GetStarted.test.js, src/ignitus-Navigation/Components/Navigation.test.js
added tests for Navigation and GetStarted component
Fixes #38
=> added tests for navigation and GetStarted component

src/ignitus-ProfessorLogin/Components/login.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Signup.js
Login and signup links were broken because of missing /student or /professor suffixes. I've fixed with correct links. Also "Don't have an account? Sign Up" is added to student login for consistency.
Broken links.
Running in local
=> Bugfix on login / signup links

src/ignitus-Testimonial/Components/Testimonial.js
cleans up testimonial components
removes unnecessary variable creation and logging to console
#53
=> cleans up testimonials component

src/ignitus-Navigation/Components/Navigation.js
In navigation section made cursor changing with respect to context.
Made cursor changing with respect to context.
Made cursor changing with respect to context.
Fixed #112 
Tested through local developement setup.
- [`x` ] Bug fix (non-breaking change which fixes an issue)
=> fixed issue #112

.eslintrc, public/push-handler.js, src/registerServiceWorker.js, sw-precache-config.js
This PR should close #114 so
I extended the behavior of the current SW and added some linting env in order to let the client receive push notifications. See below for the demo.
I'll need to do a PR on the backend side of this issue, have I to updated the doc right now or you need to test it first ?
=> WIP(#114): wrote a push handling routing and added envs in linter

README.md
=> added debck to contributors list

README.md
Added myself in the contributor list. #127
=> added Rupeshiya to contributor

README.md
=> updated contributor's list in the readme 

package-lock.json, src/ignitus-Introduction/Components/Introduction.js, src/ignitus-Navigation/Components/Navigation.js
fix #156 
fix Scroll Effect when clicked on Navbar elements. 
Instead of adding any other npm module, I used the smooth keyword in HashLink for smooth scrolling.
To make UI/UX better we can use this feature.
https://github.com/Ignitus/Ignitus-Client-Side-Development/issues/156
By testing Locally
=> Scroll effect added

src/ignitus-WhatWeDo/Components/CardLayout.js
fix #176 
Padding has been added to improve the UI/UX
On Local system
=> Padding added

src/ignitus-About/Components/About.js, src/ignitus-Contributors/Components/Contributors.js, src/ignitus-Contributors/Styles/style.scss, src/ignitus-Partners/Components/Partners.js, src/ignitus-Partners/Styles/style.scss, src/ignitus-Team/Components/Team.js, src/ignitus-Team/Styles/style.scss
Attempts to remedy issue #173 
No changes in logic made
- [√ ] feature enhancement
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
=> Enhanced Partner image/logo styles on landing page #173

package-lock.json, src/ignitus-Routes/Styles/style.scss, src/ignitus-Routes/notFound.js, src/ignitus-Routes/publicRoutes.js
A 404 page has been created. Screenshot attached.
Issue #196 resolved.
No. ESLint has around 2000 existing errors.
=> 404 page created and routed

package-lock.json, src/ignitus-GetStarted/Styles/style.scss, src/ignitus-Testimonial/Components/Testimonial.js, src/ignitus-Testimonial/Styles/style.scss, src/shared/styles/ignitus-mixins.scss
Testimonial carousel styled
After reviewing the issue #29 design file for the testimonial carousel, I styled the component accordingly using SASS mixins and the Ignitus color variables.
Fixes issue on github page, improves aesthetics of page. 
https://github.com/Ignitus/Ignitus-Client-Side-Development/issues/29
=> Ignitus#29 Testimonial Carousel Styled

src/ignitus-About/Components/About.js, src/ignitus-Footer/Components/Footer.js, src/ignitus-Footer/Styles/style.scss, src/ignitus-GetStarted/Components/GetStarted.js, src/ignitus-GetStarted/Styles/style.scss, src/ignitus-Routes/publicRoutes.js, src/ignitus-SignUp/Components/Signup.js, src/ignitus-Team/Components/Data.js
Implemented Get Started Section UI
Using SASS and React Router, I styled the Get Started Section as well as created a route from the Sign Up button and the sign up page.
Issue#160
https://github.com/Ignitus/Ignitus-Client-Side-Development/issues/160
Tested view on multiple device sizes and browsers
=> Ignitus#160 Get Started Section UI Implemented

src/ignitus-GetStarted/Styles/style.scss
=> bg color updated to align with footer.

package-lock.json, src/ignitus-About/Components/About.js, src/ignitus-Helpers/ScrollToTopOnMount.js
Fixes the scroll of the AboutUs component which doesn't reset.
The AboutUs component would load but the screen scroll wouldn't reset so the page was scrolled to some random point.
I fixed it by resetting the scroll to the top when AboutUs component is mounted.
Fixes issue #206 
I checked to make sure that the problem wasn't repeating again. 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
=> Fix AboutUs scroll

src/ignitus-Common-Auth-Student-Prof/Components/commonLoginUI.js, src/ignitus-Common-Auth-Student-Prof/Components/commonSignUpUI.js, src/ignitus-Common-Auth-Student-Prof/Styles/style.scss
=> Minor UI Fixes. 👋

src/ignitus-Common-Auth-Student-Prof/Components/commonLoginUI.js, src/ignitus-ProfessorLogin/Components/login.js, src/ignitus-ProfessorSignUp/Components/Signup.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Signup.js
Added react-router Link removed href.
=> added react-router Link removed href

src/ignitus-Introduction/Components/Introduction.js
=> Spelling Fixes

src/ignitus-Dashboard-Header/Components/dashBoardHeader.js, src/ignitus-Dashboard-Header/Containers/dashBoardHeaderContainer.js, src/ignitus-Dashboard-Header/Containers/index.js, src/ignitus-Dashboard-Header/index.js, src/ignitus-Dashboard-Header/reducers.js, src/ignitus-ProfessorSignUp/Components/Signup.js, src/ignitus-Routes/protectedRoutes.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentLogin/actionTypes.js, src/ignitus-StudentLogin/actions.js, src/ignitus-StudentLogin/reducers.js, src/ignitus-StudentSignUp/Components/Signup.js
=> UI & BUG Fixes 🚀

src/ignitus-Dashboard-Header/Components/dashBoardHeader.js, src/ignitus-Dashboard-Header/Styles/style.scss
=> dashboard UI Updated 🚀

src/ignitus-Dashboard/Components/Dashboard.js, src/ignitus-Introduction/Styles/style.scss
UI Updates Dashboard Header  👋 🚀.
=> UI Updates 👋

package-lock.json, src/ignitus-Common-Auth-Student-Prof/Components/Constants.js, src/ignitus-Common-Auth-Student-Prof/Components/commonLoginUI.js, src/ignitus-Common-Auth-Student-Prof/Components/commonSignUpUI.js, src/ignitus-Common-Auth-Student-Prof/Styles/style.scss, src/ignitus-GetStarted/Styles/style.scss, src/ignitus-Introduction/Components/Constants.js, src/ignitus-Introduction/Components/Introduction.js, src/ignitus-ProfessorLogin/Components/Constants.js, src/ignitus-ProfessorLogin/Components/login.js, src/ignitus-ProfessorSignUp/Components/Constants.js, src/ignitus-ProfessorSignUp/Components/Signup.js, src/ignitus-StudentLogin/Components/Constants.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Constants.js, src/ignitus-StudentSignUp/Components/Signup.js, src/ignitus-Team/Styles/style.scss
Changes some CSS and images to load from GCP and SVG
=> Css changes and svg images

src/ignitus-CoreTeam/Components/Data.js, src/ignitus-CoreTeam/Components/Team.js, src/ignitus-CoreTeam/Styles/style.scss
Changes for increased scalability for image on hover on team UI, show  social media icon, change the links for the icons accordingly.
When mouse is hovered on the cards of the /aboutus link, the card is scaled 1.6 times and the social media icons are displayed. On mouse out event they are returned to original size without social media icons.
The links to the social media icons are given and tested. 
Solves issue described in #169.
UI changes are tested in localhost. There are no functionality change.
- [X ] Bug fix (non-breaking change which fixes an issue)
=> Fix for add hover effect in Team UI - #169

src/ignitus-Introduction/Styles/style.scss, src/ignitus-WhatWeDo/Components/Card.js, src/ignitus-WhatWeDo/Components/CardLayout.js, src/ignitus-WhatWeDo/Styles/style.scss
CSS changes to What we Provide? section.
Changes include
a) Reduce the width of the cards in what we provide section.
b) Make the cards responsive
c) Remove unwanted padding from top.
d) Cards are made equal height.
#226 
The UI is tested to be responsive
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] My code follows the code style of this project.
- [X ] I have read the **CONTRIBUTING** document.
=> Implement What we provide? UI  #226

src/ignitus-Api/constants.js, src/ignitus-Api/index.js, src/ignitus-Team/sagas.js
Show list of backend contributors from Ignitus-rest-api.
Closes #197
=> Show contributors of Ignitus-rest-api

src/ignitus-CoreTeam/Components/Team.js, src/ignitus-Dashboard-Header/Components/dashBoardHeader.js, src/ignitus-Routes/privateRoute.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Signup.js, src/ignitus-Team/Components/Team.js, src/ignitus-Testimonial/Components/Testimonial.js
Added prop types to the components which don't have it
It makes sure all props have correct types.
Fixes #39 
Tested locally. There was no console errors and everything worked as usual after the changes.
=> feat: Add prop types

src/ignitus-Footer/Components/Footer.js, src/ignitus-Footer/Components/__snapshots__/Footer.test.js.snap, src/ignitus-Footer/Styles/style.scss
Added class `col-6` to make footer columns good on Mobile and Tablet.
Added  `<hr className="clearfix w-100 d-md-none" />` to make space between social icons and menu row.
Earlier the footer was too long and was looking quite empty. It's reduced now and looks good.
Fixed #221  
I opened the website in all viewports.
On Desktop
On Mobile
=> Footer Layout Improved on Tablet and Mobile Viewport

src/ignitus-Navigation/Components/Navigation.js, src/ignitus-Navigation/Styles/style.scss
=> Add solid background color to navbar in mobile viewport

src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Signup.js, src/shared/styles/ignitus-components-common.scss
- Modification of CSS of error/alert messages
Fixes #218 
- For email validation,added one more state variable called invalidEmail.
- Changed positioning and color of error/alert messages
=> Fix CSS of alert messages

src/ignitus-ProfessorLogin/Components/login.js, src/ignitus-ProfessorSignUp/Components/Signup.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentLogin/Styles/style.scss, src/ignitus-StudentSignUp/Components/Signup.js, src/shared/styles/ignitus-components-common.scss
=> Add toggle password visiblity button

src/ignitus-Testimonial/Components/Testimonial.js, src/ignitus-Testimonial/Styles/style.scss
=> New testimonial

src/ignitus-Testimonial/Components/Testimonial.js
=> Added Interval to auto slide.

package-lock.json, src/ignitus-Api/index.js, src/ignitus-Team/selectors.js
=> Add filter to contributors to avoid repetition

src/ignitus-WhatWeDo/Components/Data/index.js
=> Fix typo 'desination' -> 'destination'

src/ignitus-Testimonial/selectors.test.js
PR for #354 
Fixed a small detail of a broken test and now it passes.
I ran `npm run test` and now it passes
=> Fix unit test

src/ignitus-Navigation/Styles/style.scss
Fixes the but in the nav bar
fixes #316 
Bug no longer appears by resizing from dev tools
=> fix: Bug in nav bar

package-lock.json, package.json
=> Husky fix 🔨

src/ignitus-ProfessorLogin/Components/login.js, src/ignitus-StudentLogin/Components/Login.js, src/shared/Components/Login/Constants.js, src/shared/Components/Login/Login.js
Professor login shares almost **same properties** as Student login. So here is the approach of SharedLogin component which can be used by both login components.
=> Reusable component

src/ignitus-Internals/index.js, src/ignitus-StudentLogin/Components/Login.js, src/ignitus-StudentSignUp/Components/Signup.js, src/shared/Components/Login/Login.js
=> Minor fixes.

src/ignitus-CoreTeam/Styles/index.ts
top margin reduced to `5em`.
Fixes issue #549
=> Top margin reduced fixes issue #549

src/ignitus-Testimonial/Styles/style.scss
fixes #572 
Added the required media query to hide the testimonials , at width of 576px.
=> Added fix to issue 572, testimonials hide up in mobile devices

src/ignitus-Footer/Styles/style.scss, src/ignitus-GetStarted/Styles/style.scss, src/ignitus-Introduction/Styles/style.scss
fixes #574 
Changes added:
- code from px to rem for footer, get started, introduction (seperate commits)
- added compatibility fix issue for background-clip
=> Issue fix 574

.github/CONTRIBUTION/CONTRIBUTION.md
=> Update contribution guidelines

src/ignitus-ProfessorSignUp/Components/Signup.js
=> master > develop 🧨

.hound.yml
fixes #570 
Changes Made in : **.hound.yml**
=> Added TypeScript support with Hound

src/ignitus-Api/constants.ts, src/ignitus-Team/Components/Team.tsx, src/ignitus-Team/Styles/index.ts
Restrict Contributors to 14. Kindly tell the link of viewing all the contributors. For now github link has been attached to it.
=> Restrict Contributors to 14 value and show all on github link

src/ignitus-Team/Components/Team.tsx
=> Deployment Hotfix 🔨

src/ignitus-Api/constants.ts, src/ignitus-HomePage/ignitus-Testimonial/Components/Testimonial.js
Client updated as per upcoming schema updates on rest-api new release. ☘️🚀☘️.
=> Client updated as per upcoming changes on rest-api. ☘️🚀☘️.

src/ignitus-Authentication/ignitus-StudentLogin/sagas.js, src/ignitus-HomePage/ignitus-Testimonial/Components/Testimonial.js, src/ignitus-Shared/Components/ignitus-AuthenticationComponents/Login/Login.js
=> Authentication broken fix 🔨☘️

src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.jsx, src/ignitus-Authentication/ignitus-StudentLogin/actions.js, src/ignitus-Authentication/ignitus-StudentLogin/selectors.js, src/ignitus-Authentication/ignitus-StudentSignUp/Components/Signup.jsx, src/ignitus-Authentication/ignitus-StudentSignUp/actions.js, src/ignitus-Authentication/ignitus-StudentSignUp/selectors.js, src/ignitus-UtilityFunctions/utilityFunctions.js
fixes #399 
Made replacements for the lodash methods and kept them under ignitus-UtilityFunctions.
The functions dose'nt cover all the edge cases as lodash methods since they didn't seem a necessity based on how you were using the method. However the methods will work same way you would expect them to work  based on your inputs on the codebase.
=> Added replacement for lodash methods under ignitus-UtilityFunctions

package-lock.json, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/typography.ts, src/ignitus-UserInterfaceBook/Components/Atoms/interfaceColors/constants.ts, src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/interfaceIcons.tsx, src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTypography/Components/interfaceTypography.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
=> UI Kit changes 🎯

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
=> [Interface Book]: Separate scroll of Side navigation & Content

src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/types.ts
Interface navigation recursion implementation 🔨
=> Interface navigation implemented using recursion 🔨.

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
=> Remove unwanted space of sidebar.

src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.tsx, src/ignitus-Authentication/ignitus-StudentLogin/Containers/loginContainer.js, src/ignitus-Authentication/ignitus-StudentLogin/actionTypes.js, src/ignitus-Authentication/ignitus-StudentLogin/actions.js, src/ignitus-Authentication/ignitus-StudentLogin/reducers.js, src/ignitus-Authentication/ignitus-StudentLogin/types.ts, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/SignUp.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Containers/studentContainer.js, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/actionTypes.ts, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/actions.ts, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/reducers.ts, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/types.ts
Possible fix #757 
Tested on all possible cases. Still an audit from maintainers is required.
=> Flaky behavior of Student signup & login.

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/defaultMultiMediaInput.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/styles.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/types.ts
=> [UIKit]: Expansion of text area inside Multimedia Input UI

src/ignitus-Routes/ignitus-PublicRoutes/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/Navigation.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Styles/style.scss, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/types.ts
Possible fix #629 
Dynamic navbar only on selected routes, Constant elsewhere.
=> Keep white background on navbar constant in Home and About page

src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.tsx
=> Clear error message on unvisiting student Login page

.github/workflows/pr-preview.yml
Fix of [checkout error](https://github.com/Ignitus/Ignitus-client/runs/579416356?check_suite_focus=true)
=> fix(pr-preview): Fix error by performing force checkout.

src/ignitus-Shared/ignitus-Utilities/Components/Link/index.tsx, src/ignitus-Shared/ignitus-Utilities/Components/Link/link.test.tsx, src/ignitus-Shared/ignitus-Utilities/Components/Link/link.tsx, src/ignitus-Shared/ignitus-Utilities/Components/Link/utils.ts
Implementation of ```Link``` component which takes care of ```rel``` attribute properly.
=> [ignitus-Shared]: Added Link component

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
Fixes #780 
Reference [here](https://github.com/emotion-js/emotion/issues/183#issuecomment-432609510)
=> fix: browser console error.

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/atoms.ts, src/ignitus-Shared/index.ts
Fix #795 
Each component/utility under ```ignitus-Shared``` are available in index file. 
Next step should be to utilize this index in all shared component.
=> [ignitus-Shared]: index file which contains all components.

package-lock.json, package.json, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/__snapshots__/defaultButtonWithIcon.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/defaultButtonWithIcon.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/defaultCheckbox.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/defaultCheckbox.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/__snapshots__/defaultDropdown.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/defaultDropdown.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/__snapshots__/defaultIconInput.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/defaultIconInput.test.tsx
- Added dev deps ```enzyme-to-json``` & ```jest-emotion```.
- Added tests for few components of ```ignitus-Shared```.
=> [ignitus-Shared]: Unit tests

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/__snapshots__/defaultPasswordInput.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/defaultPasswordInput.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/types.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/defaultInput.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/defaultInput.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/defaultInput.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/types.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/__snapshots__/defaultMultiMediaInput.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/defaultMultiMediaInput.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
- Added tests for ```DefaultPasswordInput, DefaultInput & DefaultMultiMediaInput```
- Removed ```state``` prop in ```DefaultPasswordInput```, it was unnecessary.
- Added ```handleChange``` prop in ```DefaultInput```
=> Unit tests

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/__snapshots__/defaultSearchInput.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/defaultSearchInput.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/__snapshots__/defaultTag.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/defaultTag.test.tsx
- Complete unit tests for atoms.
#519
=> [ignitus-Shared/atoms]: unit tests

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/__snapshots__/Layer.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/styles.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/types.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/style.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/style.ts, src/ignitus-Shared/index.ts
- ```Layer``` component was repeating with few modification & can be generalized. 
-  Added  ```CommonLayer``` component & implemented it without affecting UI.
=> [ignitus-sideNavigation]: Refactoring

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/__snapshots__/DashBoardOpportunity.test.tsx.snap
=> added test for ignitus-DashBoardOpportunity

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/styles.ts, src/ignitus-Shared/index.ts, src/ignitus-UserInterfaceBook/Components/Molecules/interfaceScrollBar/Components/index.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Fixes issue: #671 
Added `ignitus-ScrollBar` component under `Molecules` at `/interface/scrollBar` route.
=> Added Scroll Bar component

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/index.test.tsx
=> Added test for ignitus-UnderConstruction

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/index.test.tsx
=> Added unit test for Side Profile

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.tsx
=> Added unit test for ignitus-ProfileCard

package.json
@Marvin9 see if these changes are relevant. 🚀
=> Moved to devDependencies 🔨

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/styles.ts, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/types.ts, src/ignitus-Shared/index.ts, src/ignitus-UserInterfaceBook/Components/Molecules/interfaceModal/index.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Renaming the current overlay component to modal, because I need to implement an overlay for https://github.com/Ignitus/Ignitus-client/issues/682 but the existing one is not exactly it, its a modal.
=> Rename overlay to modal

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalShare/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalShare/Components/index.test.tsx
=> added test for modal share component

src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
=> display overlay logout message

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageCard/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageCard/styles.ts, src/ignitus-Shared/index.ts, src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageCard/Components/index.tsx, src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageCard/constants.ts, src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageCard/types.ts, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
=> Add message cards to interface

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/styles.ts
=> Fixed inline-checkbox

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/styles.ts, src/ignitus-Shared/index.ts, src/ignitus-UserInterfaceBook/Components/Atoms/interfaceLoader/Components/index.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
=> Convert Ignitus loader into CSS

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/index.tsx
=> fix navbar issue

src/ignitus-AboutPage/ignitus-Team/Components/index.tsx, src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/index.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.tsx
Removed all useEffect warnings
=> removed all useEffect warnings

src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/index.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/index.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/index.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Styles/style.ts, src/ignitus-Authentication/ignitus-StudentSignUpFlow/index.tsx, src/ignitus-Authentication/ignitus-StudentSignUpFlow/style.ts, src/ignitus-Routes/ignitus-AuthenticationRoutes/index.tsx
Resolves #876 
Preview Link: https://deploy-preview-887--peaceful-nightingale-55a1b7.netlify.app/flow/studentSignUpFlow
=> Replaced SignUp progress image with Component

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/constants.ts
fixed the join link in Nav menu.
=> fixed the join link in Nav menu

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalHooray/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalHooray/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/ToggleButtoninterface.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/ToggleButtoninterface.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/__snapshots__/DashBoardOpportunity.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/__snapshots__/Layer.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/index.test.tsx
=> updated all unit tests

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/__snapshots__/defaultTag.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/defaultTag.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.test.tsx
=> updated unit tests for ignitus-Atom

.eslintrc.json, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx
Disabled eslint warnings to temporarily disable the useEffect exhaustive-deps warnings.
=> disabled eslint warnings

public/index.html, src/App.css
=> added preload to webfonts

src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/styles.ts, src/ignitus-Shared/index.ts, src/ignitus-UserInterfaceBook/Components/Molecules/interfaceModalApply/Components/index.tsx, src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Fixes #919
Preview URL: https://deploy-preview-923--peaceful-nightingale-55a1b7.netlify.app/interface/modalApply
=> added modalApply component

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.tsx
added test for notification component
=> added test for notification component

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/Components/__snapshots__/index.test.tsx.snap, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/Components/index.test.tsx
added unit test for modal apply in issue [https://github.com/Ignitus/Ignitus-client/issues/930](https://github.com/Ignitus/Ignitus-client/issues/930)
=> unit test for modal apply

public/index.html
=> added preconnect in links to preconnect to required origins

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
closes #940 
Kindly review the same. :smile:
=>  Fixing the issue for redirect for smaller screen when clicking on navbar

src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.test.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.tsx, src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/types.ts, src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNotifications/Components/index.tsx
Added prop to handle remove notification event.
=> feat: Props update of ignitus-Notifications
